# Generated by Django 5.2.9 on 2026-01-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_userprofile_phone_number_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
